### PR TITLE
Throw exception when configuration values set to nil.

### LINKED ISSUE #2: Setting config to nil produces cryptic error message
When setting the config variables to nil you'll receive the following error when calling `.image_url`:

```
!! #<TypeError: no implicit conversion of nil into String>
```

I ran into this problem, because I'm using ENV variables in my initializer and accidentally forgot to set a value. This results in the ShareMeow config variables being set no nil, overriding the defaults and `.image_url` producing the cryptic error above.

Fortunately there's a limited codebase here so debugging this is rather painless, but I still think a more descriptive error message when calling `.image_url` or using nil as a configuration value would be handy.

### PR DESCRIPTION
**Pull request by marckohlbrugge**
Fixes #2 

Not sure this is the best solution as my Ruby skills are quite basic, but figured I'd at least give it a shot to return the favor. Probably best to do some more testing before integrating it 😬

### CODE REVIEW

File: lib/helpers/configuration.rb [hunk 1]
```diff
@@ -20,10 +20,11 @@ def configuration
     yield self
   end
 
-  def define_setting(name, default = nil)
+  def define_setting(name, default = nil, allow_nil: true)
     class_variable_set("@@#{name}", default)
 
     define_class_method "#{name}=" do |value|
+      raise "#{name} cannot be nil." if value.nil? && !allow_nil
```
Comment (mscoutermarsh) [inline lib/helpers/configuration.rb]: LOVE IT! :heart: 

Couple of suggestions:
- Since we don't have any config settings that can be nil. I think you could remove `allow_nil`.
- For the error message, how about. `"ShareMeowClient.#{name} was not set. Please set it in your ShareMeow initializer"`

Comment (marckohlbrugge) [inline lib/helpers/configuration.rb]: Agreed! Will fix these issues.

In `README.md` you suggest creating an initializer named `share_meow.rb` whereas the classname is `ShareMeowClient`. Is this on purpose? I'd say `share_meow_client.rb` might be  better. The reason I ask is because in your suggested error message you refer to the "ShareMeow initializer" whereas I'd say "ShareMeowClient initializer".

Comment (mscoutermarsh) [inline lib/helpers/configuration.rb]: Good point! :smile: 

Should be `share_meow_client.rb` and ShareMeowClient initializer.

**Comment by mscoutermarsh** [comment]
<3
